# Generated by Django 3.0.7 on 2020-07-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200716_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myprofile',
            old_name='User',
            new_name='user',
        ),
    ]
